#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Stop the service if running
        if [ -d /run/systemd/system ]; then
            if systemctl is-active --quiet qd-dhcpd.service; then
                systemctl stop qd-dhcpd.service || true
            fi
            systemctl disable qd-dhcpd.service || true
        fi
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
