#!/usr/bin/env python3
import sys
import os

def usage():
    print("Usage: replacestring -a \"search\" \"replace\" file")
    sys.exit(1)

if len(sys.argv) < 5:
    usage()

if sys.argv[1] != "-a":
    usage()

search = sys.argv[2]
replace = sys.argv[3]
filename = sys.argv[4]

try:
    with open(filename, 'r') as f:
        content = f.read()
    
    new_content = content.replace(search, replace)
    
    with open(filename, 'w') as f:
        f.write(new_content)
        
except Exception as e:
    print(f"Error: {e}")
    sys.exit(1)
